-- phpMyAdmin SQL Dump
-- version 4.4.10
-- http://www.phpmyadmin.net
--
-- Host: localhost:8889
-- Generation Time: Aug 22, 2017 at 02:04 PM
-- Server version: 5.5.42
-- PHP Version: 7.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `folding_poetry`
--

-- --------------------------------------------------------

--
-- Table structure for table `emails`
--

CREATE TABLE `emails` (
  `id` int(11) NOT NULL,
  `email` text NOT NULL,
  `poem_id` int(11) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `poems`
--

CREATE TABLE `poems` (
  `id` int(11) NOT NULL,
  `poem` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `line_count` int(11) NOT NULL,
  `bg_color` text COLLATE utf8mb4_bin NOT NULL,
  `styles` text CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=188 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Dumping data for table `poems`
--

INSERT INTO `poems` (`id`, `poem`, `last_update`, `line_count`, `bg_color`, `styles`) VALUES
(1, 'jag <br>har  inte varit noga med att ta <br>till vara pÃ¥ allt <br>som jag ser hÃ¤r<br>idag ', '2016-12-10 00:53:36', 0, '', ''),
(2, 'hey <br>hey jag vet att du inte ser<br>mig hÃ¤r eller nÃ¥gonsin <br>nÃ¥gonsin ', '2016-12-10 00:56:10', 3, '', ''),
(13, 'wow I get to start<br>what now this is really something<br>isn''t it? yeah. I think it is<br>dont you go <br>do it ', '2016-12-12 19:24:44', 0, '', ''),
(19, 'help me out<br>I''m struggling to get by<br>it''s lonely sometimes when I''m taking my<br>time ', '2016-12-12 19:35:58', 0, '', ''),
(38, 'asd<br>asd coo<br>asdf oeo<br>asdf ', '2016-12-12 20:01:42', 3, '', ''),
(39, 'now evryting is working<br>again I think<br>I hope. <br><br>I need to rest , I need to sleep<br>I need to do too much <br>... ', '2016-12-12 20:04:44', 5, '', ''),
(40, 'hello<br>test its working!!!<br>I love it very very veyr very <br>much ', '2016-12-12 22:32:21', 3, '', ''),
(41, 'okay let''s go on<br>! come on<br>hey what about the other one<br>what? what do you mean?<br>what do You? think of me<br>now ', '2016-12-12 22:39:47', 5, '', ''),
(42, 'asdkjf<br>asdkfj hey<br>asdf cool <br>hety oacl<br>aoc sdfkj<br>asdlj ', '2016-12-12 23:01:42', 5, '', ''),
(43, 'hey<br>again here<br>we are what are you<br>doing i don''t know<br>asdf ', '2016-12-12 23:05:24', 4, '', ''),
(44, 'come on now<br>hey asdf<br>asdf asdfljn<br>asdfkj ', '2016-12-12 23:06:21', 3, '', ''),
(45, 'asdflkh<br>asdlkfjh sdfl<br>asldk sdlfkj<br>asdj asdflkj<br>asdj alskdj<br>asdpj ', '2016-12-12 23:10:06', 5, '', ''),
(46, 'let''s start something new<br>I want to see you now<br>I need to see<br>if it works now<br>sdg asdf<br>asf asdf<br>asdf ', '2016-12-13 22:55:49', 6, '', ''),
(47, 'asdf<br>asdf sdf<br>asdf asdf<br>asf asdf<br>sdf sadf<br>asdf asdf<br>asdf asdf<br>asdf asdf<br>asdf asdf<br>dsfg sdfg<br>adfg ', '2016-12-13 23:02:00', 10, '', ''),
(48, 'asdfjh<br>asdflj asdf<br>asdf asdf<br>sdf sadf<br>asdf fds<br>asfd ', '2016-12-13 23:12:01', 5, '', ''),
(49, 'asdf<br>asdf asdf<br>sdf sdf<br>sdf sdf<br>sdf asdf<br>asdf asdf<br>asdf asdf<br>sadf ', '2016-12-13 23:14:52', 7, '', ''),
(50, 'asdf<br>asdf sadflkj<br>asdf sadf<br>asdf asdf<br>asdf sadf<br>asdf asdf<br>asdf ', '2016-12-14 15:11:40', 6, '', ''),
(51, '1<br>2 campers went to school<br>they never cam back to where they were<br>they never knew ', '2016-12-14 15:32:31', 3, '', ''),
(52, 'I''ve never seen you here before <br>where do you live?<br>Far.<br> How far?<br>Too far to go. ', '2016-12-14 16:18:09', 3, '', ''),
(53, 'asdflkasjdnfklajsdnf asldkfjasld<br>sldfjasldkfjasl is just jibberish<br>I know is just jibberish<br>I know is just jibberish<br>I know is just jibberish<br>I know is just jibberish<br>I know you can feel it too<br>I know you hear them<br>coming in the night, turning<br>you <br> into something you''re not<br>you are ', '2016-12-14 19:57:12', 10, '', ''),
(54, 'asdf<br> asdf<br>asdf asdf<br>asdf ', '2016-12-14 20:07:43', 3, '', ''),
(55, 'sadf<br>asdf asdj<br>asd asdoij<br>asd ', '2016-12-14 20:12:28', 3, '', ''),
(56, 'Hello now let''s do a long text <br>shall we try it ?<br>Yes let''s try this again <br>hey this again <br>hey ', '2016-12-14 20:38:31', 3, '', ''),
(57, 'I never knew just how to say it,<br>I always knew we couldn''t be<br>so what''s going on?<br>I don''t know ', '2016-12-14 21:34:01', 3, '', ''),
(58, '<br> <br> asdf<br> <br> <br> <br> <br> ', '2016-12-14 21:44:36', 7, '', ''),
(59, 'Do I get a space before?<br>Maybe  , maybe not<br>i don''t knowyet let''s see<br>here we go ', '2016-12-14 22:03:12', 3, '', ''),
(60, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not ', '2016-12-17 21:10:30', 0, '', ''),
(61, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not ', '2016-12-17 21:10:30', 0, '', ''),
(62, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not  there<br>anymore ', '2016-12-17 21:11:05', 0, '', ''),
(63, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not  there<br>anymore ', '2016-12-17 21:11:05', 0, '', ''),
(64, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not  there<br>anymore  so what do we do?<br>Talk? ', '2016-12-17 21:11:26', 0, '', ''),
(65, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not  there<br>anymore  so what do we do?<br>Talk? ', '2016-12-17 21:11:26', 0, '', ''),
(66, 'again<br>hello  this is cool<br>now im done  , finished, famished and beat<br>I have no idea  what I am<br>no more  what I am<br>no more  what I am<br>no more  what I am<br>no more  or less<br>to you  hassle no more talk<br>I''m not  there<br>anymore  so what do we do?<br>Talk?  No not now<br>I''m tired of it ', '2016-12-17 21:13:16', 0, '', ''),
(67, ' hello im number two<br>they say  I could never try another thing<br>in my life  I''ve loved them all<br>oh  the horror<br>oh the fear  what is holding me back<br>I''m tired ', '2016-12-17 21:31:39', 5, '', ''),
(68, ' let''s start something new<br>and keep going  , keep fighting it<br>hold it back  and give it to me<br>now ', '2016-12-17 21:58:30', 3, '', ''),
(69, ' Love is in the air<br>I''m flying  too high<br>now  I''m nearly there<br>now I''m here  now im free<br>going to sleep ', '2016-12-17 22:01:24', 4, '', ''),
(70, ' hello wil it update?<br>dont know  what''s going on now<br>hey  what''s going on<br>yo  what''s going on<br>here  what up<br>dog ', '2016-12-17 22:12:10', 3, '', ''),
(71, ' what up<br>dog ', '2016-12-17 22:12:25', 4, '', ''),
(72, ' hello man<br>im not  hello man<br>im not  here right now<br>I''m sorry  that I let you down<br>so easily ', '2016-12-17 22:16:43', 3, '', ''),
(73, ' I''m trying to set the length<br>myself  yourself<br>me  and you are two seperate things<br>I know now  , I know it''s awfully sad<br>to see  what you mean when you say<br>what you''re not  saying<br>what you''re not  giving back<br>I take  there''s nothing<br>here ', '2016-12-17 22:24:31', 9, '', ''),
(74, ' Now then<br>let''s see  YES<br>it worked  again i think<br>okay going  to bed <br>now!  when this is done...<br>okay oaky  last line here <br>we go ', '2016-12-17 22:31:59', 6, '', ''),
(75, ' Goodmorning<br>old sport  whatever happened to you?<br>I''m most  grateful for you existence<br>In   these dark dark times <br>old friend ', '2016-12-18 10:21:06', 4, '', ''),
(76, ' hello let''s go<br>hey  what''s your name?<br>Busy  doing nothing at all<br>right now ', '2016-12-18 12:09:43', 3, '', ''),
(77, ' I''m not sitting here to do well<br>it''s for me  okay okay<br>okay  let''s see if we can do this<br>thing  is true then <br>well  let''s try again or what do you<br>say? <br>  I''m not sure what to do<br>here  come <br>on  I wanna seeee<br>it ', '2016-12-20 10:42:18', 8, '', ''),
(78, ' I''m starting another one<br>What do you say  When there''s nothing to <br>do?  not read too much dear<br>its a fault  to not let us know<br>what  to not let us know<br>what  do you think about this?<br>will it work? ', '2016-12-20 18:53:15', 5, '', ''),
(79, ' let''s try again and this time it<br>s for real  and hey<br>cool  to know you<br>again ', '2016-12-20 19:01:06', 3, '', ''),
(80, ' Everything is alright<br>I don''t  know what to say anymore<br>I''m broke  and feeling it<br>fast ', '2016-12-20 19:20:50', 3, '', ''),
(81, ' next attempt<br>to get there  faster than ever<br>you go  to school today<br>right? ', '2016-12-20 20:08:39', 3, '', ''),
(82, ' here we go again<br>hey  let''s do this again<br>shall we  try it together<br>or not ', '2016-12-20 20:08:55', 3, '', ''),
(83, ' I don''t really know where it<br>leads  to nothing <br>at all  I dont<br> see  you now<br>and then  I left you for another<br>do you see  me now?<br>do you know?  what?<br>The lion  never said anything about me<br>Did it?  Yes it did.<br>Yes, we did ', '2016-12-20 23:54:41', 9, '', ''),
(84, ' next<br>time  and time again<br>we fall in love  with ourselves sometimes<br>I know ', '2016-12-21 10:07:03', 3, '', ''),
(85, ' here we go cookie<br>I see you  here noe<br>hey  let me in, let me see you <br>let me hear  you say it<br>again  , really?<br>Again  and again they run and shoot<br>me  and you<br>far away  , never alone, always lonely<br>and I  know that it''s not forever<br>or something  else I''m missing?<br>Yeah ', '2016-12-21 10:27:25', 10, '', ''),
(86, ' Let''s do this thing<br>hey  babe, take a walk on the wild<br>side  hey <br>hey ', '2016-12-21 10:36:00', 3, '', ''),
(87, ' Hey is this the last?<br>Yep  it''s true<br>I know its so  goddamn cold<br>in here  goddamn cold<br>in here  goddamn cold<br>in here  it''s me<br>man  it''s me<br>man  I''m hungry<br>now  let''s eat<br>it up  again. and down<br>and up  else that''s missing<br>today  is a good day for me<br>skyes are blue  ', '2016-12-21 19:54:38', 9, '', ''),
(88, ' go to sleep may<br>I''m dying  here, and your describing<br>the water  is cold<br>here  we go<br>again  it''s me<br>here  we go again<br>friend  come over<br>I''m singing  in the rain <br>just singing ', '2016-12-21 19:55:35', 8, '', ''),
(89, ' Now let''s see what happens<br>here  I am<br>now  I know<br>now I see  what happened here today<br>let''s talk  about this<br>I''m not sure  what to feel about it<br>now  let''s see<br>hmm  I see<br>what about you?  Yeah sure, <br>Im game ', '2016-12-21 21:58:09', 9, '', ''),
(90, ' hello?<br>yes  I know, but why?<br>Why do I   care so much about it<br>why bother  asking. I''m drunk.<br>Youre beautiful  and rational<br>like a bee  in the night, I sting<br>anyone  who sees me<br>is alive  and kicking<br>just like ', '2016-12-21 21:59:48', 8, '', ''),
(91, ' I''m doing it again<br>to myself  you see me rolling<br>to myself  whenever <br>you call  me up <br>late  at night I''m turning turning<br>around  here no one cares<br>anymore  than you do<br>and I know  it sucks to be fucking far<br>but with you ', '2016-12-21 22:03:53', 8, '', ''),
(92, ' bam bam bam<br>bam  beach summer sun horse roses win<br>child tea sun  and nothing more<br>just water  under the bridge<br>nd now  it doesn''t matter anymore<br>what  do you need<br>from me  to you<br>and ever more ', '2016-12-21 22:11:20', 7, '', ''),
(93, ' hello again <br>it''s me  again<br>hey  you<br>lets dance ', '2016-12-21 22:22:53', 3, '', ''),
(94, ' The bird is flying ever higher<br>into   the wild and beyond the forest<br>I rest  with you now<br>love ', '2016-12-21 22:25:09', 3, '', ''),
(95, ' yeah <br>yeah  in solitude<br>with myself  as a guide<br>you know  I''m not so brave<br>now  you got it <br>looks like hell ', '2016-12-21 22:34:27', 5, '', ''),
(96, ' hey let''s start anew<br>ye  you got it<br>bae  it''s me again<br>let me know ', '2016-12-21 22:36:42', 3, '', ''),
(97, ' I''m all that matters to me<br>now  you see<br>me  and you<br>I like you ', '2016-12-21 22:49:18', 3, '', ''),
(98, ' go to sleep<br>and hear  me say it again<br>to me  it don''t <br>matter ', '2016-12-21 22:51:18', 3, '', ''),
(99, ' I''m trying, I really am<br>let me see  you tonight<br>plz  let <br>me  and you<br>here  im all yours<br> here  it is<br>grandma  and I never know <br>it  doesn''t matter right?<br>whatever  you do<br>I''m gonna sing ', '2016-12-21 22:53:57', 9, '', ''),
(100, ' new poem im excited to see it<br>happen  to see me <br>again  and again and again <br>it never ends ', '2016-12-22 14:51:19', 3, '', ''),
(101, ' another one I hanvet seen<br>before  it''s too late<br>for you  i''d do anything<br>dear  me, whatever happened to <br>love ', '2016-12-22 15:46:25', 4, '', ''),
(102, ' Hello? Is there someone<br>out there?  let''s play it again<br>don''t you think  it''s okay now?<br>no, well ', '2016-12-23 22:35:10', 3, '', ''),
(103, ' Hello let''s start again<br>okay  okay okay<br>okay  I''m done<br>let me go  I wanns see<br>water running ', '2016-12-23 22:42:34', 4, '', ''),
(104, ' yeah<br>yeah  oh yeah<br>hmm  whatever happens now I dont see <br>the problem in a drink ', '2016-12-23 23:08:01', 3, '', ''),
(105, ' It''s been a long time, now I''m <br>coming back  to see you<br>now  I''m finished with this<br>so don''t leave me alone ', '2016-12-24 17:48:48', 3, '', ''),
(106, ' asdlfkj<br>  asdf<br>  jello<br> ', '2016-12-24 17:52:14', 3, '', ''),
(107, ' Let''s do this<br>again <span> and again <br>om here</span> <span style="background-color: ''" asdf<br>asdf</span> ', '2016-12-24 23:31:14', 3, '', ''),
(108, ' The second is empty<br>the first one  <span style="background-color: ''" is the bst they say<br>hey</span> <span style="background-color: #FF4242"> you are the one <br>i love</span> ', '2016-12-24 23:40:30', 3, '', ''),
(109, ' hello<br> <span style="background-color: ''" asdfiuh<br>asdifuh</span> <span class="poem-line" style="background-color: #555555"> hej<br>hej</span> <span class="poem-line" style="background-color: #AAA506"> you are the one i long to see<br>come see me</span> ', '2016-12-25 00:18:42', 4, '', ''),
(110, ' I''ve never been very much for<br>pastries <span class="poem-line" style="background-color: rgb(255, 66, 66)"> are cool and all<br>but what if we </span> <span class="poem-line" style="background-color: #A01E7D"> met tonight,<br>what if we could be</span> ', '2016-12-25 00:27:54', 3, '', ''),
(111, '<span class="poem-line" style="background-color: #0B62E6"> hello<br>aefoh</span> <span class="poem-line" style="background-color: #A01E7D"> is the real name of our lord<br>I told you</span> <span class="poem-line" style="background-color: #FF4242"> it''s the second time I gave<br>it away. I''m finished</span> ', '2016-12-25 22:57:18', 3, '', ''),
(112, '<span class="poem-line" style="background-color: rgb(19, 155, 153)"> I''ve got to go <br>But i long to</span> <span class="poem-line" data-color="#A01E7D"> have you near me now<br>I see</span> <span class="poem-line" data-color="#139B99"> you''ve made it <br>here</span> ', '2016-12-25 23:18:36', 3, '', ''),
(113, '<span style="background-color: #AAA506"> let me go let me go<br>to sleep</span> <span class="poem-line" data-color="#A01E7D"> into darkness <br>I''m going to be</span> <span class="poem-line" data-color="#A01E7D"> over the hill<br>soon</span> ', '2016-12-25 23:26:46', 3, '', ''),
(114, '<span class="poem-line" style="background-color: rgb(19, 155, 153)"> I''m picking the color now, let''s<br>see what we get</span> <span class="poem-line" data-color="#F932FC"> when we dont fight <br>anymore</span> <span class="poem-line" data-color="#FF4242"> I sgoo theu sleep <br>with ou tmorrq</span> <span class="poem-line" data-color="#A01E7D"> by my side <br>I long to be</span> ', '2016-12-25 23:27:33', 4, '', ''),
(115, '<span class="poem-line" data-color="#0B62E6"> Okay it''s working<br>let''s sleep</span> <span class="poem-line" data-color="#A01E7D"> <br><br>goodnight paul</span> <span class="poem-line" data-color="#FF4242"> , sleep tight<br>and well</span> ', '2016-12-25 23:34:41', 3, '', ''),
(116, '<span class="poem-line" data-color="#AAA506"> Soon everyone will be good again<br>It''s time</span> <span class="poem-line" data-color="#555555"> to go see our friend again<br>I''m longing for</span> <span class="poem-line" data-color="#AAA506"> the day when all has <br>gone away</span> <span class="poem-line" data-color="#555555"> to play in ever present days<br>Days on end, day and nigh</span> ', '2016-12-26 09:10:06', 4, '', ''),
(117, '<span class="poem-line" data-color="#555555"> I''m starting again<br>because</span> <span class="poem-line" data-color="#A01E7D"> it''s still light outside<br>I''m pushing</span> <span class="poem-line" data-color="#0B62E6"> on into the night<br>all the people walk</span> ', '2017-01-01 18:51:34', 3, '', ''),
(118, '<span class="poem-line" data-color="#555555"> I''m new, I''m fresh<br>so clean</span> <span class="poem-line" data-color="#139B99"> and yet so humbly filthy<br>I''m sure</span> <span class="poem-line" data-color="#139B99"> it''s nothing we haven''t seen<br>before</span> <span class="poem-line" data-color="#555555" data-location="Toronto, Canada"> it''s too late<br>I''m gone</span> ', '2017-01-11 04:40:56', 4, '', ''),
(119, '<span class="poem-line" data-color="#F932FC"> It doesn''t help much <br>thinking </span> <span class="poem-line" data-color="#139B99"> It doesn''t help much <br>thinking </span> <span class="poem-line" data-color="#0B62E6"> about tomorrow won''t help much<br>today</span> <span class="poem-line" data-color="#FF4242"> is the last day of this <br>whatever it is</span> <span class="poem-line" data-color="#A01E7D"> it''s not a crime, it''s not wrong<br>And it''s not</span> <span class="poem-line" data-color="#FF4242"> what I thought <br>it would be</span> <span class="poem-line" data-color="#FF4242"> magical, an adventure<br>but no, </span> <span class="poem-line" data-color="#139B99" data-location="Toronto, Canada"> it''s too late now<br>to say sorry</span> ', '2017-01-11 04:49:01', 7, '', ''),
(120, '<span class="poem-line" data-color="#555555"> I''m starting a new one bae<br>It''s all good </span> <span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> now, the snow is silent<br>the rain </span> <span class="poem-line" data-color="#555555" data-location="Toronto, Canada"> was never sure just where <br>to go</span> <span class="poem-line" data-color="#555555" data-location="Toronto, Canada"> to hear me say it <br>louder yet</span> <span class="poem-line" data-color="#0B62E6" data-location="Ottawa, Canada"> louder still<br>it goes </span> <span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> with out saying, i''m sick<br>it''s true</span> <span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> though, I saw it <br>and whatever happens now</span> ', '2017-01-15 23:03:32', 7, '', ''),
(121, '<span class="poem-line" data-color="#FF4242"> yo man<br>what up</span> <span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> sdf<br>sadf</span> <span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> is not really a word<br>It''s more of a feeling</span> ', '2017-01-15 23:16:13', 3, '', ''),
(122, '<span class="poem-line" data-color="#139B99" data-location="Toronto, Canada"> I''m all ears but I don''t get <br>most of it <br></span> <span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> comes off quite easily<br>the rest</span> <span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada"> is just testing me <br>seeing</span> <span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada"> as it''s just another night<br>let''s not fret for passiveness sake</span> ', '2017-01-15 23:39:21', 4, '', ''),
(123, '<span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada"> Hello gotta be a baguette<br>like now</span> <span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada"> or like <br>forever</span> <span class="poem-line" data-color="#139B99" data-location="Toronto, Canada"> and ever <br>we float</span> ', '2017-01-15 23:55:15', 3, '', ''),
(124, 'Hello Im a poem', '2017-01-18 02:30:42', 4, '', ''),
(125, '<span class="poem-line" data-color="#555555" data-location="Toronto, Canada"> yo hey i''m back<br>again</span> <span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada"> and again <br>let''s escape to</span> <span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada"> whatever hole is left for us<br>to see</span> <span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> I''m sure we''ll make it<br><br>what do you say?</span> ', '2017-01-18 02:39:11', 4, '', ''),
(126, '<span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> Now here''s the real bummer<br>I know you like</span> <span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">, I know you love<br><br>But whatever</span> <span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada"> it is i''m like whatevs<br>hey</span> <span class="poem-line" data-color="#A01E7D" data-location="Toronto, Canada">, what''s your name?<br><br>Juliet</span> ', '2017-01-18 03:08:57', 4, '', ''),
(127, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">gone and gone<br>tres joli</span><span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">, is that what she said? <br>je ne se pas</span><span class="poem-line" data-color="#AAA506" data-location="">tres bien mon amour<br><br>tres bien</span>', '2017-01-18 03:30:27', 3, '', ''),
(128, '<span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada">hey hey <br>what''s my name?</span><span class="poem-line" data-color="#139B99" data-location="Toronto, Canada">Is it hard to tell?<br>No no no</span><span class="poem-line" data-color="#0B62E6" data-location="">, don''t do it <br>witch</span>', '2017-01-18 03:34:10', 3, '', ''),
(129, '<span class="poem-line" data-color="rgb(160, 30, 125)" data-location="Toronto, Canada"> Okay I''m getting up soon<br>just a minute</span> <span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">, i*M not done<br>yet</span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">again it happens to me<br>soon</span>', '2017-01-18 15:41:56', 3, '', ''),
(130, '<span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">it''s all abotu the replace<br>here</span><span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">, we can''t go on<br>like this</span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">we just can''t<br><br>please</span>', '2017-01-18 15:50:14', 3, '', ''),
(131, '<span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada">OMG it''s always staring me in the face<br>od </span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">, maybe too early too code<br><br>Maybe not </span><span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada">at all, I''m not sure<br>anymore </span>', '2017-01-18 15:52:14', 3, '', ''),
(132, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">hello<br>I''m here </span><span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">, just for you<br>dear </span><span class="poem-line" data-color="#555555" data-location="Toronto, Canada">me, what happened<br>hear? </span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">Here?? But why?<br>I don''t understand </span>', '2017-01-18 15:56:04', 4, '', ''),
(133, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">omg i think I got it!<br>Celebration </span><span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada">    time tonight<br><br>do didi di di  </span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">, deee di di <br><br>WO hoo! </span><span class="poem-line" data-color="#555555" data-location="Toronto, Canada">Ceeeeelebration time <br>a yeah </span>', '2017-01-18 15:57:39', 4, '', ''),
(134, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">what about the comma dude<br>I don''t see it </span><span class="poem-line" data-color="#A01E7D" data-location="Toronto, Canada">, it''s not here<br>aymore </span><span class="poem-line" data-color="#555555" data-location="Toronto, Canada">, what about now?<br>huh? </span>', '2017-01-18 15:59:17', 3, '', ''),
(135, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">hmm don''t know anymore<br>whats going on</span><span class="poem-line" data-color="#555555" data-location="Toronto, Canada">, could you tell me?<br>please</span><span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada">let me know<br>hey</span>', '2017-01-18 16:04:01', 3, '', ''),
(136, '<span class="poem-line" data-color="#555555" data-location="Toronto, Canada">come on come on now<br>let it be </span><span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada">me who comes near to the flame<br>of the field </span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">, of the turn im in<br>let it come ove </span><span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada">r me like a fueled flame<br>in the night </span>', '2017-01-18 16:06:35', 4, '', ''),
(137, '<span class="poem-line" data-color="#AAA506" data-location="Toronto, Canada">nonono not now eaither%l1%hmmm%l2%</span><span class="poem-line" data-color="#555555" data-location="Toronto, Canada">, how does it look%l1%like?%l2%</span><span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> what? what?<br>%l2s%espresso</span>', '2017-01-18 16:18:47', 3, '', ''),
(138, '<span class="poem-line" data-color="#A01E7D" data-location="Toronto, Canada"> wow wow yet agin I happened<br>it started</span><span class="poem-line" data-color="#A01E7D" data-location="Toronto, Canada">,  just like it never knew<br>what to think</span><span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> of lying around all day<br><br>shrinking</span><span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada">,  growing, shrinking, growing<br><br>Ever present in the field of barley</span>', '2017-01-18 16:22:43', 4, '', ''),
(139, '<span class="poem-line" data-color="#139B99" data-location="Toronto, Canada">okay losing sight%l1%i want coffe bu</span>%l2%<span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada">it''s not too good I think.%l1%Come over</span>%l2%<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada">, let''s talk it through%l1%I''m keen to</span>%l2%<span class="poem-line" data-color="#139B99" data-location="Toronto, Canada"> see it again<br>let''s start</span>', '2017-01-18 16:50:04', 4, '', ''),
(140, '<span class="poem-line" data-color="#139B99" data-location="Toronto, Canada"> let''s see<br>if</span> <span class="poem-line" data-color="#F932FC" data-location="Toronto, Canada"> you know<br>then why</span><span class="poem-line" data-color="#0B62E6" data-location="Toronto, Canada"> do you try so hard Ã§a va<br>Ã§a va</span>', '2017-01-18 16:50:45', 3, '', ''),
(141, '<span class="poem-line" data-color="#FF4242" data-location="Toronto, Canada"> Starting anew, the game''s afoot<br>I''m terribly</span><span class="poem-line" data-color="#A01E7D" data-location="Toronto, Canada">,  terribly sorry about this<br><br>Let''s not talk</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> about things we cannot change<br>There''s enough</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> to say, but not enough to do<br>Thank you</span>', '2017-07-01 12:46:34', 4, '', ''),
(142, '<span class="poem-line" data-color="#FF4242" data-location="Stockholm, Sweden"> The weights may change very quickly<br>It''s not</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> very thought through, or<br>flattering for</span><span class="poem-line" data-color="#555555" data-location="Stockholm, Sweden"> you<br>or for me</span>', '2017-07-01 12:51:05', 3, '', ''),
(143, '<span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> Coolers coolers<br>hey hey hey</span><span class="poem-line" data-color="#49bdff" data-location="Stockholm, Sweden"> what''s your name bae bae bae<br>you''re not who</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> I think you are<br>You''re always</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> the one to talk too fast to me<br>too soon</span>', '2017-07-01 13:34:44', 4, '', ''),
(144, '<span class="poem-line" data-color="#00938a" data-location="Stockholm, Sweden"> now I''ve got it<br>don''t let me do</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> it again,<br>don''t leave me</span><span class="poem-line" data-color="#49bdff" data-location="Stockholm, Sweden"> lose it again like I''ve lost<br>so many</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> to start<br>don''t leave me lose it again</span>', '2017-07-01 13:45:37', 4, '', ''),
(145, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> Hey okay okay<br>hey</span><span class="poem-line" data-color="#00938a" data-location="Stockholm, Sweden"> I''m not sure how I want it to be<br>let''s try</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> it at least<br>it can''t hurt</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> to try<br>can it?</span>', '2017-07-01 14:28:32', 4, '', ''),
(146, '<span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> You told me I could never go it alone<br>I said it was</span><span class="poem-line" data-color="#00938a" data-location="Stockholm, Sweden"> too late for you to give me<br>advice</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> me to be something else<br>But I don''t</span><span class="poem-line" data-color="#00938a" data-location="Stockholm, Sweden"> need to<br>I don''t I don''t need I don''t</span>', '2017-07-01 14:35:31', 4, '', ''),
(147, '<span class="poem-line" data-color="#d40098" data-location="Stockholm, Sweden"> Hej I*m another one for the running<br>Another dog in</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> the making<br>Another leap</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> into the void<br>of misery</span>', '2017-07-01 14:43:18', 3, '', 'text-transform: uppercase;font-style: normal;'),
(148, '<span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> It seems almost too repetitaite<br>dont you think</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> it''s like I don''t know<br>I don''t know</span><span class="poem-line" data-color="#d40098" data-location="Stockholm, Sweden">,  whatever you say boss<br>I know, you feel like going</span>', '2017-07-01 14:46:27', 3, '', 'text-transform: lowercase;font-style: normal;'),
(149, '<span class="poem-line" data-color="#d40098" data-location="Stockholm, Sweden"> Don''t give me that look<br>I''m doing my</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> best, I hope you can see that<br><br>Throw me a bone</span><span class="poem-line" data-color="#d40098" data-location="Stockholm, Sweden">,  I''ll eat it up<br><br>promise</span>', '2017-07-02 10:22:39', 3, '', 'text-transform: default;font-style: italic;'),
(150, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> Hello?<br>I''m alone</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden">,  or at least that''s how I feel<br>I guess it''s</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> never as bad as it may seem<br>Considering</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> how little time has passed<br>I''d like to be kind to myself</span>', '2017-07-02 10:40:39', 4, '', 'text-transform: uppercase;font-style: normal;'),
(151, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> What now then,<br>do I just</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> give up?<br>I can''t see it</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden">,  I''m tired of wating<br>I wanna run</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> <br><br>But I don''t</span><span class="poem-line" data-color="#ff0000" data-location="Stockholm, Sweden"> want to leave you<br>fuck it</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> I don''t even know anymore<br>I don''t know</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> who I am<br>maybe that''s okay<br><br></span>', '2017-07-02 10:59:58', 7, '', 'text-transform: default;font-style: normal;'),
(152, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> Hello?<br>I''m alone</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> and lonely<br>I wish I could</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> give you more<br>Ah fuck what the fuck do I do</span>', '2017-07-02 11:02:19', 3, '', 'text-transform: uppercase;font-style: italic;'),
(153, '<span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> Maybe it doesn''t work that way<br>Who do I ask</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I guess no one else would know<br>as well as I<br><br></span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> It''s just a matter of time<br>before</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> it hits me<br><br>Just don''t let</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> it hit me too hard<br><br>I floating too</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> high to hit the ground running<br><br>You should know</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> you''re always giving me advice<br><br>thanks<br><br></span>', '2017-07-02 11:05:47', 7, '', 'text-transform: uppercase;font-style: italic;'),
(154, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> Okay let''s see what we''ve got<br>It''s so</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> exciting right now<br>I can hardly</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> contain it<br>Let''s go, right</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> to bed my dear<br><br>I''m exhausted</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> from the heat<br>Leave me be</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden">,  I''m begging you?<br>Weird thing</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> to ask if I may say so mayself<br><br>For myself</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> I''ve always fancied tea in the<br>parking lot</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden">,  as if that would help the<br>children sing</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> <br><br>Please let it be done with</span>', '2017-07-03 11:28:04', 10, '#f9f9f9', 'text-transform: lowercase;font-style: normal;color: #202020;font-weight: 800;font-family: Shrikhand;'),
(155, '<span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> How do I want it to look in the end<br>Would it be</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> ever changing?<br>Maybe that''s</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> too busy<br><br>Let me think</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> about it for a minute<br>God it''s gettin</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> hot today, bring in the ice<br>tea</span>', '2017-07-03 11:33:17', 5, '#0bffbd', 'text-transform: uppercase;font-style: normal;color: #202020;font-weight: 800;font-family: Rakkas;'),
(156, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> I''m not sure how to put it<br>It just comes</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> to me, and I roll with it<br>don''t take it</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> too personally dear<br>It''s only loce</span>', '2017-07-03 13:25:50', 3, '#fffc00', 'text-transform: default;font-style: normal;color: #202020;font-weight: 800;font-family: Shrikhand;'),
(157, '<span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> If ever we should build a house<br>Let''s have</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> chickens<br><br>Please, don''t</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> laugh, it makes me feel old<br>I''m too old</span>', '2017-07-03 13:28:53', 3, '#00fffb', 'text-transform: lowercase;font-style: italic;color: #fffc00;font-weight: 300;font-family: Rakkas;'),
(158, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> You and I should go away some day, just<br>the two of us</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> could start a war<br>a war on</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> everything that god forgot<br>I''m sure there''s something</span>', '2017-07-03 13:55:58', 3, '#202020', 'text-transform: default;font-style: normal;color: #ff2f67;font-weight: 100;font-family: Shrikhand;'),
(159, '<span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> I''m not at all bored by this<br>really</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden">,  is that what you think?<br>Well bloody</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> hell then<br><br>I''m going to find another drinking buddy</span>', '2017-07-03 14:00:15', 3, '#9eff3d', 'text-transform: default;font-style: normal;color: #202020;font-weight: 300;font-family: Shrikhand;'),
(160, '<span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> You can''t say I didn''t try<br><br>I promise</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> I won''t give in too easily<br>this time</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden">,  it''s more than a promise<br><br>It''s not just about love</span>', '2017-07-03 18:28:08', 3, '#202020', 'text-transform: uppercase;font-style: normal;color: #ff2f67;font-weight: 800;font-family: Ubuntu;'),
(161, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> you can''t be serious<br>what about</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> the other day?<br><br>What about it?</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> <br><br>I don''t know</span><span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> yet, I''m figuring myself out<br>Thanks for listening</span>', '2017-07-03 20:13:33', 4, '#0bffbd', 'text-transform: lowercase;font-style: normal;color: #00fffb;font-weight: 100;font-family: Arbutus Slab;'),
(162, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m talking to myself again<br>I''m longing</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> for every breath away from pain<br>It''s not that</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> I''m not breathing<br>it''s just pain finds its way into many</span>', '2017-07-03 20:45:49', 3, '#F932FC', 'text-transform: default;font-style: italic;color: #fffc00;font-weight: 400;font-family: Shrikhand;'),
(163, '<span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> OK go<br>go go go</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> you go ashole<br>leave me alone</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> well you leave me alone now<br>seriously go go</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> what the actuall fuck is wrong<br>with you, GO!!!</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> AWAY!!!! i dont want to talk to<br>i want to write poetry. okay bye<br><br></span>', '2017-07-03 21:01:02', 5, '#9eff3d', 'text-transform: default;font-style: italic;color: #fffc00;font-weight: 500;font-family: Shrikhand;'),
(164, '<span class="poem-line" data-color="#00fffb" data-location="Stockholm, Sweden"> NOW THEN<br>Please</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> WFT what happend to you to  make<br>you like this??</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> well what make you a bag of shit<br>as fuck. any way. I LOVE YOU</span>', '2017-07-03 21:05:57', 3, '#0043ef', 'text-transform: default;font-style: normal;color: #F932FC;font-weight: 100;font-family: Arbutus Slab;'),
(165, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m not as excited anymore<br>Could you</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> please let me go<br>I''m telling</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> you to stop and go,<br>stop and go</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> - stop to see<br>It''s sunny outside</span>', '2017-07-05 13:13:46', 4, '#202020', 'text-transform: default;font-style: normal;color: #f9f9f9;font-weight: 400;font-family: Arbutus Slab;'),
(166, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m not talking about the horses anymore<br>I''m over it</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden">,  and don''t go thinking I''m not<br>Because I am</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> not afraid to tell you how<br>I feel</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> to tired and fuzzy in my head<br>Let go</span>', '2017-07-05 13:23:24', 4, '#f9f9f9', 'text-transform: default;font-style: italic;color: #202020;font-weight: 300;font-family: Ubuntu;'),
(167, '<span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> Hello again<br>omg</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> its again<br>again</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> and again<br>om</span>', '2017-07-05 13:46:25', 3, '#202020', 'text-transform: default;font-style: italic;color: #fffc00;font-weight: 800;font-family: Arbutus Slab;'),
(168, '<span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> Don''t let me say it too many times<br>I''m telling you</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> it''s not my fault, it never is<br>So come on, let</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> me have it<br><br>I''m not the one</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> to bother the dead<br>with troubles</span>', '2017-07-05 14:03:45', 4, '#0043ef', 'text-transform: lowercase;font-style: italic;color: #f9f9f9;font-weight: 800;font-family: Ubuntu;'),
(169, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m saying the same things over and over<br>Again, and</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> again, again and again<br>We''re here</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> now, so let''s talk<br>I''m seriously</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> mad right<br>now</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> I''m talking about<br>you</span>', '2017-07-05 14:13:29', 5, '#0043ef', 'text-transform: default;font-style: normal;color: #f9f9f9;font-weight: 400;font-family: Rakkas;'),
(170, '<span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> It''s only love and that is all<br>So why should I</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> feel the way I do<br>Oh</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> that sorrow I feel in this<br>Room</span><span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> s are talking<br>to me all night, let me go</span>', '2017-07-05 14:13:51', 4, '#202020', 'text-transform: lowercase;font-style: italic;color: #ff2f67;font-weight: 400;font-family: Rakkas;'),
(171, '<span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> Come on now<br>where did you g</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> o<br>now</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> I''m not talking about you any<br>more than you</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> know<br>that</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> is good<br>hey</span>', '2017-07-05 14:19:08', 5, '#f9f9f9', 'text-transform: lowercase;font-style: italic;color: #202020;font-weight: 800;font-family: Rakkas;'),
(172, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> come on<br>what''s</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> the matter<br>Fine I get it</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden">,  and I''m not mad about it going<br>to hell</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> with all your conventions<br>This is</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> my only way of saying it<br>if I don''t</span>', '2017-07-05 14:22:42', 5, '#f9f9f9', 'text-transform: default;font-style: italic;color: #fffc00;font-weight: 500;font-family: Ubuntu;'),
(173, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> now<br>then</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m<br>not</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> your choice to make<br>But let''s not say things too often</span>', '2017-07-05 14:23:26', 3, '#F932FC', 'text-transform: default;font-style: normal;color: #202020;font-weight: 400;font-family: Shrikhand;'),
(174, '<span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> You have got me going on again and again<br>Don''t you know</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''ve been trying to<br>tell you</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> to come again<br>tell you to</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> go away slowly, I''m not happy<br>so I''ll let you</span><span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> go again<br><br>I guess I''ll let you go again</span>', '2017-07-05 20:37:54', 5, '#ff2f67', 'text-transform: uppercase;font-style: normal;color: #F932FC;font-weight: 300;font-family: Rakkas;'),
(175, '<span class="poem-line" data-color="#F932FC" data-location="Stockholm, Sweden"> Now then<br>What''s</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> up with all the hanging around<br>I''m troubled</span><span class="poem-line" data-color="#ff2f67" data-location=", Sweden"> <br><br>No, not really</span>', '2017-07-06 07:37:44', 3, '#f9f9f9', 'text-transform: lowercase;font-style: normal;color: #ff2f67;font-weight: 800;font-family: Shrikhand;'),
(176, '<span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> Hello mister postman, let me see you<br>I''m not coming</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> home tonight ma<br>You never treat</span><span class="poem-line" data-color="#0043ef" data-location=", Sweden"> me as well as you said you would<br>let me be</span><span class="poem-line" data-color="#ff2f67" data-location=", Sweden"> hopeless and helpless again<br>I''d rather not lose hope</span>', '2017-07-06 07:45:33', 4, '#0043ef', 'text-transform: lowercase;font-style: normal;color: #ff2f67;font-weight: 500;font-family: Ubuntu;');
INSERT INTO `poems` (`id`, `poem`, `last_update`, `line_count`, `bg_color`, `styles`) VALUES
(177, '<span class="poem-line" data-color="#202020" data-location=", Sweden"> Hello all of you<br>Sitting in my</span><span class="poem-line" data-color="#0043ef" data-location=", Sweden"> own space<br>Sitting on my</span><span class="poem-line" data-color="#202020" data-location=", Sweden"> hey<br>go</span>', '2017-07-06 07:55:57', 3, '#f9f9f9', 'text-transform: uppercase;font-style: normal;color: #202020;font-weight: 100;font-family: Rakkas;'),
(178, '<span class="poem-line" data-color="#f9f9f9" data-location=", Sweden"> Okay last one before coffee<br>Im  a longing</span><span class="poem-line" data-color="#f9f9f9" data-location=", Sweden"> for belonging. I wanna hope but<br>not too much</span><span class="poem-line" data-color="#fffc00" data-location=", Sweden"> to hear you say<br>hey</span><span class="poem-line" data-color="#fffc00" data-location=", Sweden">, <br><br>grow up</span>', '2017-07-06 08:26:30', 4, '#D800FF', 'text-transform: uppercase;font-style: italic;color: #fffc00;font-weight: 400;font-family: Anton;'),
(179, '<span class="poem-line" data-color="#0043ef" data-location=", Sweden"> I have another thought about the fall<br>of man</span><span class="poem-line" data-color="#0043ef" data-location="Malmo, Sweden"> and dog, you don''t see much<br>these days</span><span class="poem-line" data-color="#ff2f67" data-location="Malmo, Sweden"> don''t come running fast enough<br>these dogs</span><span class="poem-line" data-color="#0043ef" data-location="Malmo, Sweden"> are nuthin but cheap cats<br>longing for the woods</span>', '2017-07-16 21:40:49', 4, '#f9f9f9', 'text-transform: lowercase;font-style: italic;color: #0043ef;font-weight: 400;font-family: Shrikhand;'),
(180, '<span class="poem-line" data-color="#ff2f67" data-location="Stockholm, Sweden"> I''m talking about the good times,<br>The lookyloos</span><span class="poem-line" data-color="#f9f9f9" data-location="Malmo, Sweden"> have all gone to sleep<br>All the</span><span class="poem-line" data-color="#fffc00" data-location="Malmo, Sweden"> help in the world could never<br>use me</span><span class="poem-line" data-color="#202020" data-location=", "> til<br>it over</span>', '2017-07-17 20:27:27', 4, '#D800FF', 'text-transform: uppercase;font-style: normal;color: #202020;font-weight: 800;font-family: Shrikhand;'),
(181, '<span class="poem-line" data-color="#fffc00" data-location="Malmo, Sweden"> omg i here<br>again</span><span class="poem-line" data-color="#ff2f67" data-location=", "> and again and again<br>It goes</span><span class="poem-line" data-color="#fffc00" data-location="Stockholm, Sweden"> like ðŸ”¥ðŸ”¥ðŸ”¥<br>And then I''m like ðŸ’‹</span>', '2017-07-20 21:12:42', 3, '#202020', 'text-transform: lowercase;font-style: italic;color: #fffc00;font-weight: 400;font-family: Questrial;'),
(182, '<span class="poem-line" data-color="#fffc00" data-location="Malmo, Sweden"> it''s never as bad as it seems<br>sometimes</span><span class="poem-line" data-color="#202020" data-location="Malmo, Sweden"> it''s not as easy as it seems<br>but you should</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> go again<br>Right?</span>', '2017-07-20 21:13:38', 3, '#f9f9f9', 'text-transform: default;font-style: normal;color: #0043ef;font-weight: 500;font-family: Rakkas;'),
(183, '<span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> I''m like come on<br>don''t let it</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> Iâ€™m trying to see the ðŸ³<br>in the ðŸŒŠ</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> woods<br>I roam</span><span class="poem-line" data-color="#D800FF" data-location="Stockholm, Sweden"> here too now<br>okay</span>', '2017-07-20 22:39:16', 4, '#0bffbd', 'text-transform: uppercase;font-style: normal;color: #D800FF;font-weight: 800;font-family: Anton;'),
(184, '<span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> im feeling ðŸ˜´<br>But ðŸ‰ Makes</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> it so hard<br>to breath</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> is to find another way of seeing<br>I know what''s up</span>', '2017-07-20 23:42:17', 3, '#fffc00', 'text-transform: uppercase;font-style: normal;color: #f9f9f9;font-weight: 100;font-family: Yeseva One;'),
(185, '<span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> This is my last goodbye<br>let it sing</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> it<br>to see the 🔥 i</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> need to get going<br>it never happen</span><span class="poem-line" data-color="#D800FF" data-location="Stockholm, Sweden"> to an angel<br>are you an 😇</span><span class="poem-line" data-color="#202020" data-location="Stockholm, Sweden"> ?<br>I''m just asking, the 🥑 is on its way</span>', '2017-07-21 20:11:23', 5, '#ff2f67', 'text-transform: uppercase;font-style: normal;color: #202020;font-weight: 500;font-family: Anton;'),
(186, '<span class="poem-line" data-color="#ffe700" data-location="Stockholm, Sweden"> 🥑🥑🥑🥑<br>🥑🥑</span><span class="poem-line" data-color="#f9f9f9" data-location="Stockholm, Sweden"> U+1F345<br>U+1F345</span><span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> is the only 🥑 in my life<br>I''m not broke</span><span class="poem-line" data-color="#0043ef" data-location="Sweden">,  I am just so happy to have a<br>son. John<br><br></span><span class="poem-line" data-color="#202020" data-location="Sweden"> we are almost done. it wont be<br>long then im</span><span class="poem-line" data-color="#202020" data-location="Sweden"> sadf<br>asd</span>', '2017-08-14 16:28:08', 6, '#ffe700', 'text-transform: uppercase;font-style: normal;color: #202020;font-weight: 400;font-family: Yeseva One;'),
(187, '<span class="poem-line" data-color="#0043ef" data-location="Stockholm, Sweden"> Hello<br>I''m testing</span><span class="poem-line" data-color="#ff2f67" data-location="Sweden"> it again,<br>hopefully it</span><span class="poem-line" data-color="#ffe700" data-location="Sweden"> is not too long til honesty<br>takes over me once more</span>', '2017-08-14 16:28:48', 3, '#0bffbd', 'text-transform: lowercase;font-style: italic;color: #ffe700;font-weight: 100;font-family: Rakkas;');

-- --------------------------------------------------------

--
-- Table structure for table `working_poems`
--

CREATE TABLE `working_poems` (
  `id` int(11) NOT NULL,
  `working_poem` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_line` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `curr_line_count` int(11) NOT NULL DEFAULT '0',
  `target_line_count` int(11) NOT NULL DEFAULT '0',
  `in_use` tinyint(1) NOT NULL DEFAULT '0',
  `color` text CHARACTER SET latin1 NOT NULL,
  `styles` text CHARACTER SET latin1 NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=138 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Dumping data for table `working_poems`
--

INSERT INTO `working_poems` (`id`, `working_poem`, `last_line`, `curr_line_count`, `target_line_count`, `in_use`, `color`, `styles`, `last_update`) VALUES
(130, '<span class="poem-line" data-color="#f9f9f9" data-location="Sweden">%l1s%does it not go away?%l1e%%l2s%say%l2e%</span><span class="poem-line" data-color="#202020" data-location="Sweden">%l1s%it again%l1e%%l2s%hey%l2e%</span>', 'hey', 2, 3, 0, '#202020', '', '2017-08-15 11:43:02'),
(131, '', '', 0, 0, 0, '', '', '2017-08-14 16:34:56'),
(132, '', '', 0, 0, 0, '', '', '2017-07-21 18:59:10'),
(133, '', '', 0, 0, 0, '', '', '2017-07-21 18:59:04'),
(134, '', '', 0, 0, 0, '', '', '2017-07-20 23:42:17'),
(135, '', '', 0, 0, 0, '', '', '2017-07-21 18:57:56'),
(136, '', '', 0, 0, 0, '', '', '2017-08-14 16:28:08'),
(137, '', '', 0, 0, 0, '', '', '2017-08-14 16:28:48');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `emails`
--
ALTER TABLE `emails`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `poems`
--
ALTER TABLE `poems`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `working_poems`
--
ALTER TABLE `working_poems`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `emails`
--
ALTER TABLE `emails`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `poems`
--
ALTER TABLE `poems`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=188;
--
-- AUTO_INCREMENT for table `working_poems`
--
ALTER TABLE `working_poems`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=138;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
